"use client";

import React, { createContext, useContext, useState, useEffect } from "react";
import { useRouter, usePathname } from "next/navigation";

export type Language = "en" | "vi" | "es" | "ru" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations = {
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.features": "Features",
    "nav.installation": "Installation",
    "nav.news": "News",
    "nav.wiki": "Wiki",
    "nav.community": "Community",
    "nav.download": "Download Now",
    "community.title": "We believe in a future where players own their tools.",
    "community.desc": "LF Launcher is a fully open-source project on GitHub, where you can shape the future of gaming with us. Join the LF Launcher family on Discord and Telegram.",
    "hero.badge": "Version 1.0.0 out now",
    "hero.title": "LF Launcher – Driven by Players.",
    "hero.subtitle": "Not trying to be the most popular launcher – just focusing on being the one players truly want to use for the long term.",
    "hero.download": "Download",
    "hero.changelog": "Changelog",
    "screenshot.title": "Screen",
    "screenshot.highlight": "shot",
    "features.title": "Features",
    "features.v.title": "Versions",
    "features.v.desc": "Get access to almost all versions and switch between them in an instant.",
    "features.s.title": "Settings",
    "features.s.desc": "Tweak every nook and cranny to your heart's content.",
    "sponsors.title": "Sponsors",
    "sponsors.desc": "We thank all the wonderful backers over at Open Collective! Support LF Launcher and its development by ",
    "sponsors.link": "becoming a backer",
    "sponsors.bmc": "Buy me a coffee",
    "footer.desc": "Not trying to be the most popular launcher – just focusing on being the one players truly want to use for the long term.",
    "footer.connect": "Connect",
    "footer.support": "Support",
    "footer.copyright": "© 2026 Lasscmone Studio",
    "footer.disclaimer": "Not affiliated with Mojang Studios.",
    "download.title": "Get LF Launcher",
    "download.subtitle": "Choose your platform and start your Minecraft journey with the most modern launcher ever made.",
    "download.latest": "Latest Release",
    "download.windows.name": "Windows",
    "download.android.name": "Android",
    "download.windows.installer": "Installer (.exe)",
    "download.windows.portable": "Portable (.zip)",
    "download.android.apk": "Download APK",
    "download.windows.feat1": "Auto-updater included",
    "download.windows.feat2": "Optimized for Windows 10/11",
    "download.windows.feat3": "Supports all Java versions",
    "download.android.feat1": "Touch optimized controls",
    "download.android.feat2": "Native controller support",
    "download.android.feat3": "Low battery consumption",
    "download.notes.title": "Release Notes",
    "about.badge": "Our Story",
    "about.hero.title": "Driven by Players, Built for the Future.",
    "about.hero.subtitle": "LF Launcher isn't just a tool; it's a commitment to creating the most refined, performance-focused, and open experience for the Minecraft community.",
    "about.value1.title": "Pure Performance",
    "about.value1.desc": "We believe a launcher should be invisible. No heavy frameworks, no bloated features—just raw speed.",
    "about.value2.title": "Privacy First",
    "about.value2.desc": "Your data belongs to you. We collect zero telemetry and track nothing. Pure privacy by design.",
    "about.value3.title": "Player Centric",
    "about.value3.desc": "Every feature we build starts with a simple question: Does this make the game better for players?",
    "about.history.title": "From a Mobile Experiment to a Cross-Platform Hub.",
    "about.history.v1.date": "August 2023",
    "about.history.v1.title": "The Android Dawn",
    "about.history.v1.desc": "LF Launcher v1.0.0 launched on Android, focusing on a simplified way to download and manage Minecraft PE versions.",
    "about.history.v2.date": "2024 - Present",
    "about.history.v2.title": "Expansion & Refinement",
    "about.history.v2.desc": "Expanding to Windows with a unified design language, bringing the same performance-first philosophy to PC players worldwide.",
    "about.cta.title": "Shape the future with us.",
    "about.cta.desc": "We are a team of passionate developers and gamers under Lasscmone Studio. Join our community and help us build the launcher players truly deserve.",
    "about.cta.discord": "Join our Discord",
    "about.cta.github": "Contribution",
    "download.notes.desc": "See what's new in the latest version of LF Launcher.",
    "download.verify.title": "Verification",
    "download.verify.desc": "Check the file integrity with MD5/SHA256 checksums.",
    "download.legacy.title": "Legacy Versions",
    "download.legacy.desc": "Need an older version? Access our complete archive.",
    "download.more": "Read more",
    "download.verify.action": "Verify files",
    "download.archive": "Browse archive",
  },
  vi: {
    "nav.home": "Trang chủ",
    "nav.about": "Giới thiệu",
    "nav.features": "Tính năng",
    "nav.installation": "Cài đặt",
    "nav.news": "Tin tức",
    "nav.wiki": "Wiki",
    "nav.community": "Cộng đồng",
    "nav.download": "Tải ngay",
    "community.title": "Chúng tôi tin vào một tương lai nơi người chơi làm chủ công cụ của chính mình.",
    "community.desc": "LF Launcher là dự án mã nguồn mở hoàn toàn trên GitHub, nơi bạn có thể cùng chúng tôi định hình tương lai của trò chơi. Hãy trở thành một phần của đại gia đình LF Launcher trên Discord và Telegram.",
    "hero.badge": "Đã ra mắt phiên bản 1.0.0",
    "hero.title": "LF Launcher – Phát triển bởi người chơi.",
    "hero.subtitle": "Không cố gắng trở thành launcher phổ biến nhất – chỉ tập trung trở thành cái tên mà người chơi thực sự muốn gắn bó lâu dài.",
    "hero.download": "Tải về",
    "hero.changelog": "Thay đổi",
    "screenshot.title": "Ảnh",
    "screenshot.highlight": " chụp",
    "features.title": "Tính năng",
    "features.v.title": "Phiên bản",
    "features.v.desc": "Truy cập gần như tất cả các phiên bản và chuyển đổi giữa chúng chỉ trong tích tắc.",
    "features.s.title": "Cài đặt",
    "features.s.desc": "Tinh chỉnh mọi ngóc ngách theo ý thích của bạn.",
    "sponsors.title": "Nhà tài trợ",
    "sponsors.desc": "Chúng tôi gửi lời cảm ơn đến tất cả những người ủng hộ tuyệt vời tại Open Collective! Hãy ủng hộ LF Launcher bằng cách ",
    "sponsors.link": "trở thành người ủng hộ",
    "sponsors.bmc": "Mời tôi ly cà phê",
    "footer.desc": "Không cố gắng trở thành launcher phổ biến nhất – chỉ tập trung trở thành cái tên mà người chơi thực sự muốn gắn bó lâu dài.",
    "footer.connect": "Kết nối",
    "footer.support": "Hỗ trợ",
    "footer.copyright": "© 2026 Lasscmone Studio",
    "footer.disclaimer": "Không liên kết với Mojang Studios.",
    "download.title": "Tải LF Launcher",
    "download.subtitle": "Chọn nền tảng của bạn và bắt đầu hành trình Minecraft với trình khởi chạy hiện đại nhất từng được tạo ra.",
    "download.latest": "Phiên bản mới nhất",
    "download.windows.name": "Windows",
    "download.android.name": "Android",
    "download.windows.installer": "Bộ cài đặt (.exe)",
    "download.windows.portable": "Bản di động (.zip)",
    "download.android.apk": "Tải xuống APK",
    "download.windows.feat1": "Bao gồm tự động cập nhật",
    "download.windows.feat2": "Tối ưu hóa cho Windows 10/11",
    "download.windows.feat3": "Hỗ trợ tất cả các phiên bản Java",
    "download.android.feat1": "Điều khiển tối ưu cho cảm ứng",
    "download.android.feat2": "Hỗ trợ tay cầm gốc",
    "download.android.feat3": "Tiêu thụ pin thấp",
    "download.notes.title": "Ghi chú phát hành",
    "about.badge": "Câu chuyện của chúng tôi",
    "about.hero.title": "Phát triển bởi Người chơi, Xây dựng cho Tương lai.",
    "about.hero.subtitle": "LF Launcher không chỉ là một công cụ; đó là lời cam kết tạo ra trải nghiệm tinh tế, tập trung vào hiệu suất và cởi mở nhất cho cộng đồng Minecraft.",
    "about.value1.title": "Hiệu suất Thuần túy",
    "about.value1.desc": "Chúng tôi tin rằng trình khởi chạy nên 'vô hình'. Không có framework nặng nề, không có tính năng thừa thãi—chỉ có tốc độ thuần túy.",
    "about.value2.title": "Quyền riêng tư là trên hết",
    "about.value2.desc": "Dữ liệu của bạn thuộc về bạn. Chúng tôi không thu thập dữ liệu từ xa và không theo dõi bất cứ điều gì. Quyền riêng tư tuyệt đối.",
    "about.value3.title": "Lấy Người chơi làm Trung tâm",
    "about.value3.desc": "Mọi tính năng chúng tôi xây dựng đều bắt đầu bằng một câu hỏi đơn giản: Điều này có làm cho trò chơi tốt hơn cho người chơi không?",
    "about.history.title": "Từ một Thử nghiệm trên Di động đến một Trung tâm Đa nền tảng.",
    "about.history.v1.date": "Tháng 8/2023",
    "about.history.v1.title": "Bình minh Android",
    "about.history.v1.desc": "LF Launcher v1.0.0 ra mắt trên Android, tập trung vào cách đơn giản hóa để tải và quản lý các phiên bản Minecraft PE.",
    "about.history.v2.date": "2024 - Hiện tại",
    "about.history.v2.title": "Mở rộng & Tinh chỉnh",
    "about.history.v2.desc": "Mở rộng sang Windows với ngôn ngữ thiết kế thống nhất, mang triết lý ưu tiên hiệu suất đến với người chơi PC trên toàn thế giới.",
    "about.cta.title": "Cùng chúng tôi xây dựng tương lai.",
    "about.cta.desc": "Chúng tôi là một đội ngũ các nhà phát triển và game thủ đam mê dưới trướng Lasscmone Studio. Hãy tham gia cộng đồng của chúng tôi.",
    "about.cta.discord": "Tham gia Discord",
    "about.cta.github": "Đóng góp",
    "download.notes.desc": "Xem có gì mới trong phiên bản LF Launcher mới nhất.",
    "download.verify.title": "Xác minh",
    "download.verify.desc": "Kiểm tra tính toàn vẹn của tệp bằng mã MD5/SHA256.",
    "download.legacy.title": "Phiên bản cũ",
    "download.legacy.desc": "Cần một phiên bản cũ hơn? Truy cập kho lưu trữ đầy đủ của chúng tôi.",
    "download.more": "Đọc thêm",
    "download.verify.action": "Xác minh tệp",
    "download.archive": "Duyệt kho lưu trữ",
  },
  es: {
    "nav.home": "Inicio",
    "nav.about": "Acerca de",
    "nav.features": "Características",
    "nav.installation": "Instalación",
    "nav.news": "Noticias",
    "nav.wiki": "Wiki",
    "nav.community": "Comunidad",
    "nav.download": "Descargar ahora",
    "community.title": "Creemos en un futuro donde los jugadores son dueños de sus propias herramientas.",
    "community.desc": "LF Launcher es un proyecto totalmente de código abierto en GitHub, donde puedes dar forma al futuro de los juegos con nosotros. Únete a la familia de LF Launcher en Discord y Telegram.",
    "hero.badge": "Versión 1.0.0 ya disponible",
    "hero.title": "LF Launcher – Impulsado por jugadores.",
    "hero.subtitle": "No intentamos ser el launcher más popular – solo nos enfocamos en ser el que los jugadores realmente quieran usar a largo plazo.",
    "hero.download": "Descargar",
    "hero.changelog": "Cambios",
    "screenshot.title": "Captura de ",
    "screenshot.highlight": "pantalla",
    "features.title": "Características",
    "features.v.title": "Versiones",
    "features.v.desc": "Obtén acceso a casi todas las versiones y cambia entre ellas en un instante.",
    "features.s.title": "Ajustes",
    "features.s.desc": "Ajusta cada rincón a tu gusto.",
    "sponsors.title": "Patrocinadores",
    "sponsors.desc": "¡Agradecemos a todos los maravillosos patrocinadores en Open Collective! Apoya a LF Launcher y su desarrollo ",
    "sponsors.link": "convirtiéndote en patrocinador",
    "sponsors.bmc": "Cómprame un café",
    "footer.desc": "No intentamos ser el launcher más popular – solo nos enfocamos en ser el que los jugadores realmente quieran usar a largo plazo.",
    "footer.connect": "Conectar",
    "footer.support": "Soporte",
    "footer.copyright": "© 2026 Lasscmone Studio",
    "footer.disclaimer": "No afiliado a Mojang Studios.",
    "download.title": "Obtener LF Launcher",
    "download.subtitle": "Elige tu plataforma y comienza tu viaje en Minecraft con el launcher más moderno jamás creado.",
    "download.latest": "Última versión",
    "download.windows.name": "Windows",
    "download.android.name": "Android",
    "download.windows.installer": "Instalador (.exe)",
    "download.windows.portable": "Portable (.zip)",
    "download.android.apk": "Descargar APK",
    "download.windows.feat1": "Actualizador automático incluido",
    "download.windows.feat2": "Optimizado para Windows 10/11",
    "download.windows.feat3": "Soporta todas las versiones de Java",
    "download.android.feat1": "Controles optimizados para pantallas táctiles",
    "download.android.feat2": "Soporte nativo para mandos",
    "download.android.feat3": "Bajo consumo de batería",
    "download.notes.title": "Notas de Lanzamiento",
    "about.badge": "Nuestra Historia",
    "about.hero.title": "Impulsado por Jugadores, Construido para el Futuro.",
    "about.hero.subtitle": "LF Launcher no solo es una herramienta; es un compromiso de crear la experiencia más refinada, enfocada en el rendimiento y abierta para la comunidad de Minecraft.",
    "about.value1.title": "Rendimiento Puro",
    "about.value1.desc": "Creemos que un lanzador debería ser invisible. Sin marcos pesados, sin funciones infladas—solo velocidad pura.",
    "about.value2.title": "Privacidad Primero",
    "about.value2.desc": "Tus datos te pertenecen. No recopilamos telemetría ni rastreamos nada. Privacidad pura por diseño.",
    "about.value3.title": "Centrado en el Jugador",
    "about.value3.desc": "Cada característica que construimos comienza con una pregunta simple: ¿Esto hace que el juego sea mejor para los jugadores?",
    "about.history.title": "De un experimento móvil a un centro multiplataforma.",
    "about.history.v1.date": "Agosto 2023",
    "about.history.v1.title": "El Amanecer de Android",
    "about.history.v1.desc": "LF Launcher v1.0.0 lanzado en Android, enfocándose en una forma simplificada de descargar y gestionar versiones de Minecraft PE.",
    "about.history.v2.date": "2024 - Presente",
    "about.history.v2.title": "Expansión y Refinamiento",
    "about.history.v2.desc": "Expandiendo a Windows con un lenguaje de diseño unificado, llevando la misma filosofía de rendimiento primero a los jugadores de PC en todo el mundo.",
    "about.cta.title": "Dale forma al futuro con nosotros.",
    "about.cta.desc": "Somos un equipo de desarrolladores y jugadores apasionados bajo Lasscmone Studio. Únete a nuestra comunidad y ayúdanos a construir el lanzador que los jugadores realmente merecen.",
    "about.cta.discord": "Únete a nuestro Discord",
    "about.cta.github": "Contribución",
    "download.notes.desc": "Mira las novedades de la última versión de LF Launcher.",
    "download.verify.title": "Verificación",
    "download.verify.desc": "Comprueba la integridad del archivo con sumas MD5/SHA256.",
    "download.legacy.title": "Versiones antiguas",
    "download.legacy.desc": "¿Necesitas una versión anterior? Accede a nuestro archivo completo.",
    "download.more": "Leer más",
    "download.verify.action": "Verificar archivos",
    "download.archive": "Explorar archivo",
  },
  ru: {
    "nav.home": "Главная",
    "nav.about": "О нас",
    "nav.features": "Возможности",
    "nav.installation": "Установка",
    "nav.news": "Новости",
    "nav.wiki": "Вики",
    "nav.community": "Сообщество",
    "nav.download": "Скачать сейчас",
    "community.title": "Мы верим в будущее, где игроки сами владеют своими инструментами.",
    "community.desc": "LF Launcher — это полностью открытый проект на GitHub, где вы можете вместе с нами формировать будущее игр. Станьте частью большой семьи LF Launcher в Discord и Telegram.",
    "hero.badge": "Версия 1.0.0 уже доступна",
    "hero.title": "LF Launcher – Создан игроками для игроков.",
    "hero.subtitle": "Мы не стремимся быть самым популярным лаунчером — мы просто создаем то, чем игроки действительно захотят пользоваться долгое время.",
    "hero.download": "Скачать",
    "hero.changelog": "Изменения",
    "screenshot.title": "Скрин",
    "screenshot.highlight": "шот",
    "features.title": "Возможности",
    "features.v.title": "Версии",
    "features.v.desc": "Получите доступ почти ко всем версиям и переключайтесь между ними мгновенно.",
    "features.s.title": "Настройки",
    "features.s.desc": "Настройте каждый уголок по своему вкусу.",
    "sponsors.title": "Спонсоры",
    "sponsors.desc": "Мы благодарим всех замечательных спонсоров на Open Collective! Поддержите LF Launcher и его разработку, ",
    "sponsors.link": "став спонсором",
    "sponsors.bmc": "Купить мне кофе",
    "footer.desc": "Мы не стремимся быть самым популярным лаунчером — мы просто создаем то, чем игроки действительно захотят пользоваться долгое время.",
    "footer.connect": "Контакты",
    "footer.support": "Поддержка",
    "footer.copyright": "© 2026 Lasscmone Studio",
    "footer.disclaimer": "Не связано с Mojang Studios.",
    "download.title": "Скачать LF Launcher",
    "download.subtitle": "Выберите свою платформу и начните свое путешествие в Minecraft с самым современным лаунчером.",
    "download.latest": "Последний релиз",
    "download.windows.name": "Windows",
    "download.android.name": "Android",
    "download.windows.installer": "Установщик (.exe)",
    "download.windows.portable": "Портативная версия (.zip)",
    "download.android.apk": "Скачать APK",
    "download.windows.feat1": "Автообновление включено",
    "download.windows.feat2": "Оптимизировано для Windows 10/11",
    "download.windows.feat3": "Поддержка всех версий Java",
    "download.android.feat1": "Оптимизированное сенсорное управление",
    "download.android.feat2": "Нативная поддержка контроллеров",
    "download.android.feat3": "Низкое энергопотребление",
    "download.notes.title": "Примечания к выпуску",
    "about.badge": "Наша история",
    "about.hero.title": "Создано игроками для будущего.",
    "about.hero.subtitle": "LF Launcher — это не просто инструмент; это стремление создать наиболее утонченный, производительный и открытый опыт для сообщества Minecraft.",
    "about.value1.title": "Чистая производительность",
    "about.value1.desc": "Мы верим, что лаунчер должен быть незаметным. Никаких тяжелых фреймворков или лишних функций — только чистая скорость.",
    "about.value2.title": "Конфиденциальность прежде всего",
    "about.value2.desc": "Ваши данные принадлежат только вам. Мы не собираем телеметрию и ничего не отслеживаем. Полная конфиденциальность по дизайну.",
    "about.value3.title": "Ориентированность на игрока",
    "about.value3.desc": "Каждая функция, которую мы создаем, начинается с простого вопроса: делает ли это игру лучше для игроков?",
    "about.history.title": "От мобильного эксперимента к кроссплатформенному хабу.",
    "about.history.v1.date": "Август 2023",
    "about.history.v1.title": "Зарождение на Android",
    "about.history.v1.desc": "LF Launcher v1.0.0 был запущен на Android, фокусируясь на упрощенном способе загрузки и управления версиями Minecraft PE.",
    "about.history.v2.date": "2024 - Настоящее время",
    "about.history.v2.title": "Расширение и улучшение",
    "about.history.v2.desc": "Расширение на Windows с единым языком дизайна, принося философию производительности игрокам на ПК по всему миру.",
    "about.cta.title": "Формируйте будущее вместе с нами.",
    "about.cta.desc": "Мы — команда увлеченных разработчиков и геймеров из Lasscmone Studio. Присоединяйтесь к нашему сообществу и помогите нам создать лаунчер, которого действительно заслуживают игроки.",
    "about.cta.discord": "Присоединиться к Discord",
    "about.cta.github": "Вклад",
    "download.notes.desc": "Узнайте, что нового в последней версии LF Launcher.",
    "download.verify.title": "Проверка",
    "download.verify.desc": "Проверьте целостность файла с помощью хеш-сумм MD5/SHA256.",
    "download.legacy.title": "Старые версии",
    "download.legacy.desc": "Нужна старая версия? Посетите наш полный архив.",
    "download.more": "Подробнее",
    "download.verify.action": "Проверить файлы",
    "download.archive": "Просмотреть архив",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.about": "حولنا",
    "nav.features": "المميزات",
    "nav.installation": "التثبيت",
    "nav.news": "الأخبار",
    "nav.wiki": "ويكي",
    "nav.community": "المجتمع",
    "nav.download": "تحميل الآن",
    "community.title": "نحن نؤمن بمستقبل يمتلك فيه اللاعبون أدواتهم الخاصة.",
    "community.desc": "LF Launcher هو مشروع مفتوح المصدر بالكامل على GitHub، حيث يمكنك تشكيل مستقبل الألعاب معنا. كن جزءاً من عائلة LF Launcher على Discord و Telegram.",
    "hero.badge": "الإصدار 1.0.0 متاح الآن",
    "hero.title": "LF Launcher – مدفوع من قبل اللاعبين.",
    "hero.subtitle": "لسنا مجرد لانشر مشهور، نحن نركز على أن نكون الخيار الذي يرغب اللاعبون في استخدامه على المدى الطويل.",
    "hero.download": "تحميل",
    "hero.changelog": "سجل التغييرات",
    "screenshot.title": "لقطة ",
    "screenshot.highlight": "الشاشة",
    "features.title": "المميزات",
    "features.v.title": "الإصدارات",
    "features.v.desc": "احصل على إمكانية الوصول إلى جميع الإصدارات تقريباً والتبديل بينها في لمح البصر.",
    "features.s.title": "الإعدادات",
    "features.s.desc": "قم بتخصيص كل زاوية وركن حسب رغبتك.",
    "sponsors.title": "الرعاة",
    "sponsors.desc": "نشكر جميع الداعمين الرائعين في Open Collective! ادعم LF Launcher وتطويره من خلال ",
    "sponsors.link": "أن تصبح داعماً",
    "sponsors.bmc": "اشتر لي قهوة",
    "footer.desc": "لسنا مجرد لانشر مشهور، نحن نركز على أن نكون الخيار الذي يرغب اللاعبون في استخدامه على المدى الطويل.",
    "footer.connect": "تواصل معنا",
    "footer.support": "الدعم",
    "footer.copyright": "© 2026 Lasscmone Studio",
    "footer.disclaimer": "غير تابع لاستوديوهات Mojang.",
    "download.title": "احصل على LF Launcher",
    "download.subtitle": "اختر منصتك وابدأ رحلتك في Minecraft مع أحدث لانشر تم إنشاؤه على الإطلاق.",
    "download.latest": "آخر إصدار",
    "download.windows.name": "Windows",
    "download.android.name": "Android",
    "download.windows.installer": "المثبت (.exe)",
    "download.windows.portable": "نسخة محمولة (.zip)",
    "download.android.apk": "تحميل APK",
    "download.windows.feat1": "تحديث تلقائي مدمج",
    "download.windows.feat2": "محسن لـ Windows 10/11",
    "download.windows.feat3": "يدعم جميع إصدارات Java",
    "download.android.feat1": "عناصر تحكم محسنة للمس",
    "download.android.feat2": "دعم أصلي لأجهزة التحكم",
    "download.android.feat3": "استهلاك منخفض للبطارية",
    "download.notes.title": "ملاحظات الإصدار",
    "about.badge": "قصتنا",
    "about.hero.title": "بإلهام من اللاعبين، من أجل المستقبل.",
    "about.hero.subtitle": "LF Launcher ليس مجرد أداة؛ إنه التزام بإنشاء تجربة أكثر دقة وتركيزاً على الأداء وانفتاحاً لمجتمع Minecraft.",
    "about.value1.title": "الأداء النقي",
    "about.value1.desc": "نحن نؤمن بأن اللانشر يجب أن يكون غير مرئي. لا توجد إطارات عمل ثقيلة، ولا ميزات زائدة—فقط سرعة خالصة.",
    "about.value2.title": "الخصوصية أولاً",
    "about.value2.desc": "بياناتك ملك لك. نحن لا نجمع بيانات القياس ولا نتتبع أي شيء. خصوصية نقية حسب التصميم.",
    "about.value3.title": "محورنا اللاعب",
    "about.value3.desc": "كل ميزة نبنيها تبدأ بسؤال بسيط: هل هذا يجعل اللعبة أفضل للاعبين؟",
    "about.history.title": "من تجربة محمولة إلى مركز متعدد المنصات.",
    "about.history.v1.date": "أغسطس 2023",
    "about.history.v1.title": "بداية أندرويد",
    "about.history.v1.desc": "تم إطلاق LF Launcher v1.0.0 على أندرويد، مع التركيز على طريقة مبسطة لتنزيل وإدارة إصدارات Minecraft PE.",
    "about.history.v2.date": "2024 - حتى الآن",
    "about.history.v2.title": "التوسع والتحسين",
    "about.history.v2.desc": "التوسع إلى Windows بلغة تصميم موحدة، وجلب فلسفة الأداء أولاً للاعبي الكمبيوتر حول العالم.",
    "about.cta.title": "شكل المستقبل معنا.",
    "about.cta.desc": "نحن فريق من المطورين واللاعبين المتحمسين تحت Lasscmone Studio. انضم إلى مجتمعنا وساعدنا في بناء اللانشر الذي يستحقه اللاعبون حقاً.",
    "about.cta.discord": "انضم إلى Discord",
    "about.cta.github": "المساهمة",
    "download.notes.desc": "تعرف على الجديد في أحدث إصدار من LF Launcher.",
    "download.verify.title": "التحقق",
    "download.verify.desc": "تحقق من سلامة الملف باستخدام بصمات MD5/SHA256.",
    "download.legacy.title": "الإصدارات القديمة",
    "download.legacy.desc": "هل تحتاج إلى إصدار أقدم؟ قم بالوصول إلى أرشيفنا الكامل.",
    "download.more": "اقرأ المزيد",
    "download.verify.action": "تحقق من الملفات",
    "download.archive": "تصفح الأرشيف",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode; initialLang: string }> = ({ children, initialLang }) => {
  const [language, setLanguageState] = useState<Language>(initialLang as Language);
  const router = useRouter();
  const pathname = usePathname();

  useEffect(() => {
    if (initialLang && initialLang !== language) {
      setLanguageState(initialLang as Language);
    }
  }, [initialLang]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);

    // Change URL to new locale
    const segments = pathname.split("/");
    segments[1] = lang;
    router.push(segments.join("/"));
  };

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations["en"]] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      <div dir={dir} className="contents">
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
